import balance from './slashCommands/balance.js';
import user from './slashCommands/user.js';
import settings from './slashCommands/settings.js';
import info from './slashCommands/info.js';
import embedbuilder from './slashCommands/embed-builder.js';
import check from './slashCommands/check.js';
import stickMessage from './slashCommands/stick-message.js';
import stp from './slashCommands/stp.js';
import membercount from './slashCommands/membercount.js';
import ping from './slashCommands/ping.js';
import rp from './slashCommands/rp.js';
import images from './slashCommands/images.js';
import roles from './slashCommands/roles.js';
import afk from './slashCommands/afk.js';
import help from './slashCommands/help.js';
import emoji from './slashCommands/emoji.js';
import slowmode from './slashCommands/slowmode.js';
import vote from './slashCommands/vote.js';
import giveaway from './slashCommands/giveaway.js';
import mod from './slashCommands/mod.js';
import customRole from './slashCommands/custom-role.js';
import selfroles from './slashCommands/self-roles.js';
import clear from './slashCommands/clear.js';
import reminder from './slashCommands/reminder.js';
import suggest from './slashCommands/suggest.js';
import shop from './slashCommands/shop.js';
import invites from './slashCommands/invites.js';

export default {
 public: {
  balance,
  user,
  settings,
  info,
  'embed-builder': embedbuilder,
  check,
  'Stick Message': stickMessage,
  stp,
  membercount,
  ping,
  rp,
  images,
  roles,
  afk,
  help,
  emoji,
  slowmode,
  vote,
  giveaway,
  mod,
  customRole,
  'self-roles': selfroles,
  clear,
  reminder,
  suggest,
  shop,
  invites,
 },
 categories: {
  'settings_moderation_anti-spam': 'moderation',
  'settings_moderation_anti-virus': 'moderation',
  'settings_moderation_auto-punish': 'moderation',
  settings_moderation_newlines: 'moderation',
  settings_moderation_invites: 'moderation',
  'settings_moderation_blacklist-rules': 'moderation',
  settings_moderation_expiry: 'moderation',
  settings_leveling_basic: 'leveling',
  'settings_leveling_multi-channels': 'leveling',
  'settings_leveling_multi-roles': 'leveling',
  'settings_leveling_level-roles': 'leveling',
  'settings_leveling_rule-channels': 'leveling',
  settings_nitro_basic: 'nitro',
  'settings_nitro_booster-roles': 'nitro',
  settings_vote_basic: 'vote',
  'settings_vote_vote-rewards': 'vote',
  'settings_roles_role-rewards': 'roles',
  'settings_roles_auto-roles': 'roles',
  'settings_roles_self-roles': 'roles',
  settings_roles_shop: 'roles',
  settings_roles_separators: 'roles',
  settings_roles_sticky: 'roles',
  'settings_roles_reaction-role-settings': 'roles',
  'settings_roles_reaction-roles': 'roles',
  'settings_roles_button-role-settings': 'roles',
  'settings_roles_button-roles': 'roles',
  settings_automation_cooldowns: 'automation',
  'settings_automation_disboard-reminders': 'automation',
  settings_automation_suggestions: 'automation',
  settings_automation_verification: 'automation',
  settings_automation_censor: 'automation',
  settings_automation_welcome: 'automation',
  settings_basic: 'utility',
  settings_logs: 'info',
  info_user: 'info',
  info_servers: 'info',
  info_server: 'info',
  info_channel: 'info',
  info_role: 'info',
  info_bot: 'info',
  info_badges: 'info',
  info_emoji: 'info',
  info_invite: 'info',
  'embed-builder_view_custom-embeds': 'utility',
  'embed-builder_view_from-message': 'utility',
  'embed-builder_create': 'utility',
  check: 'moderation',
  'Stick Message': 'utility',
  stp: 'utility',
  membercount: 'info',
  ping: 'info',
  rp_manager: 'fun',
  rp_block: 'utility',
  rp_unblock: 'utility',
  rp_blocked: 'info',
  images_neko: 'fun',
  images_husbando: 'fun',
  images_kitsune: 'fun',
  images_waifu: 'fun',
  images_shinobu: 'fun',
  images_megumin: 'fun',
  images_eevee: 'fun',
  images_holo: 'fun',
  images_icon: 'fun',
  images_okami: 'fun',
  images_senko: 'fun',
  images_shiro: 'fun',
  'roles_builders_reaction-roles': 'utility',
  'roles_builders_button-roles': 'utility',
  roles_create: 'utility',
  roles_edit: 'utility',
  roles_delete: 'utility',
  roles_info: 'info',
  roles_members: 'info',
  roles_give: 'moderation',
  roles_take: 'moderation',
  afk: 'utility',
  help_list: 'info',
  help_moderation: 'info',
  emojis_info: 'info',
  'emojis_create_from-url': 'utility',
  'emojis_create_from-file': 'utility',
  'emojis_create_from-emoji': 'utility',
  invites_create: 'utility',
  invites_info: 'info',
  invites_delete: 'utility',
  emojis_delete: 'utility',
  emojis_edit_name: 'utility',
  emojis_edit_roles: 'utility',
  slowmode: 'utility',
  user_info: 'info',
  user_avatar: 'utility',
  user_banner: 'utility',
  vote: 'info',
  giveaway_create: 'utility',
  giveaway_reroll: 'utility',
  giveaway_cancel: 'utility',
  giveaway_list: 'info',
  giveaway_end: 'utility',
  mod_tempmute: 'moderation',
  mod_unmute: 'moderation',
  mod_ban: 'moderation',
  'mod_soft-ban': 'moderation',
  'mod_temp-ban': 'moderation',
  'mod_channel-ban': 'moderation',
  'mod_temp-channel-ban': 'moderation',
  'mod_channel-unban': 'moderation',
  mod_kick: 'moderation',
  mod_warn: 'moderation',
  mod_softwarn: 'moderation',
  mod_strike: 'moderation',
  mod_unafk: 'moderation',
  mod_unban: 'moderation',
  mod_pardon_one: 'moderation',
  mod_pardon_before: 'moderation',
  mod_pardon_after: 'moderation',
  mod_pardon_between: 'moderation',
  mod_pardon_by: 'moderation',
  'mod_pardon_all-by': 'moderation',
  'mod_pardon_all-on': 'moderation',
  'custom-role': 'utility',
  'self-roles': 'roles',
  clear_all: 'utility',
  clear_user: 'utility',
  clear_between: 'utility',
  clear_match: 'utility',
  'clear_not-match': 'utility',
  'clear_starts-with': 'utility',
  'clear_ends-with': 'utility',
  clear_includes: 'utility',
  clear_links: 'utility',
  clear_invites: 'utility',
  clear_images: 'utility',
  clear_videos: 'utility',
  clear_files: 'utility',
  clear_audio: 'utility',
  clear_mentions: 'utility',
  clear_stickers: 'utility',
  clear_embeds: 'utility',
  clear_text: 'utility',
  clear_humans: 'utility',
  clear_bots: 'utility',
  reminder_create: 'utility',
  reminder_list: 'utility',
  reminder_delete: 'utility',
  reminder_edit: 'utility',
  suggest: 'utility',
  shop: 'utility',
  balance: 'utility',
 },
 names: [
  'settings',
  'info',
  'embed-builder',
  'check',
  'Stick Message',
  'stp',
  'membercount',
  'ping',
  'rp',
  'images',
  'roles',
  'afk',
  'help',
  'emoji',
  'slowmode',
  'user',
  'vote',
  'giveaway',
  'mod',
  'custom-role',
  'self-roles',
  'clear',
  'reminder',
  'shop',
  'balance',
 ],
} as const;
