import type * as Discord from 'discord.js';
import type Jobs from 'node-schedule';

/* eslint-disable max-len */
/* eslint-disable no-multi-spaces */
/* eslint-disable prettier/prettier */

export * from './ClientHelperModules/send.js';
export * from './ClientHelperModules/send.js';
export * from './ClientHelperModules/replyMsg.js';
export * from './ClientHelperModules/replyCmd.js';
export * from './ClientHelperModules/query.js';
export * from './ClientHelperModules/stp.js';
export * from './ClientHelperModules/regexes.js';
export * from './ClientHelperModules/fileURL2Buffer.js';
export * from './ClientHelperModules/memberBoostCalc.js';
export * from './ClientHelperModules/userFlagsCalc.js';
export * from './ClientHelperModules/channelRuleCalc.js';
export * from './ClientHelperModules/permCalc.js';
export * from './ClientHelperModules/getUnix.js';
export * from './ClientHelperModules/getDifference.js';
export * from './ClientHelperModules/languageSelector.js';
export * from './ClientHelperModules/bitUniques.js';
export * from './ClientHelperModules/txtFileWriter.js';
export * from './ClientHelperModules/util.js';
export * from './ClientHelperModules/errorMsg.js';
export * from './ClientHelperModules/errorCmd.js';
export * from './ClientHelperModules/permError.js';
export * from './ClientHelperModules/notYours.js';
export * from './ClientHelperModules/collectorEnd.js';
export * from './ClientHelperModules/colorSelector.js';
export * from './ClientHelperModules/loadingEmbed.js';
export * from './ClientHelperModules/arrayEquals.js';
export * from './ClientHelperModules/txtFileLinkToString.js';
export * from './ClientHelperModules/getAllInvites.js';
export * from './ClientHelperModules/getDiscordEmbed.js';
export * from './ClientHelperModules/dynamicToEmbed.js';
export * from './ClientHelperModules/embedBuilder.js';
export * from './ClientHelperModules/roleManager.js';
export * from './ClientHelperModules/getEmote.js';
export * from './ClientHelperModules/getAudit.js';
export * from './DataBase.js';
export * from './ClientHelperModules/getEmbed.js';
export * from './ClientHelperModules/getJumpLink.js';
export * from './ClientHelperModules/getLogChannels.js';
export * from './ClientHelperModules/mergeLogging.js';
export * from './ClientHelperModules/getTrueChannelType.js';
export * from './ClientHelperModules/moment.js';
export * from './ClientHelperModules/getChanged.js';
export * from './ClientHelperModules/spaces.js';
export * from './ClientHelperModules/arrayBufferToBuffer.js';
export * from './ClientHelperModules/getChannel.js';
export * from './ClientHelperModules/getSerializedChannelPerms.js';
export * from './ClientHelperModules/isManageable.js';
export * from './ClientHelperModules/getEvents.js';
export * from './ClientHelperModules/getNameAndFileType.js';
export * from './ClientHelperModules/getUser.js';
export * from './ClientHelperModules/findUserByName.js';
export * from './ClientHelperModules/getDuration.js';

export * from './ClientHelperModules/settingsHelpers.js';
export const neko = (await import('./NekoClient.js')).default;
export const constants = (await import('./Other/constants.js')).default;
export const objectEmotes = (await import('./ClientHelperModules/objectEmotes.js')).default;
export const stringEmotes = (await import('./ClientHelperModules/stringEmotes.js')).default;
export const reactionEmotes = (await import('./ClientHelperModules/reactionEmotes.js')).default;
export const mainID = '650691698409734151';
type CQ = Map<string, Map<string, Discord.APIEmbed[]>>;
type CT = Map<string, Map<string, Jobs.Job>>;
export const channelQueue: CQ = new Map();
export const channelTimeout: CT = new Map();
export const cache = (await import('./ClientHelperModules/cache.js')).default;
