import emotes from '../../UtilModules/emotes.js';

export default {
 logs: {
  automodRule: {
   create: 'https://cdn.ayakobot.com/Ayako_Assets/Events/AutomoderationRuleCreate.png',
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/AutomoderationRuleUpdate.png',
   delete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/AutomoderationRuleDelete.png',
  },
  voiceState: {
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MemberUpdate.png',
   LockedVoiceJoin: 'https://cdn.ayakobot.com/Ayako_Assets/Events/LockedVoiceCreate.png',
   VoiceJoin: 'https://cdn.ayakobot.com/Ayako_Assets/Events/VoiceCreate.png',
   StageJoin: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StageCreate.png',
   LockedVoiceLeave: 'https://cdn.ayakobot.com/Ayako_Assets/Events/LockedVoiceDelete.png',
   VoiceLeave: 'https://cdn.ayakobot.com/Ayako_Assets/Events/VoiceDelete.png',
   StageLeave: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StageDelete.png',
   LockedVoiceSwitch: 'https://cdn.ayakobot.com/Ayako_Assets/Events/LockedVoiceUpdate.png',
   VoiceSwitch: 'https://cdn.ayakobot.com/Ayako_Assets/Events/VoiceUpdate.png',
   StageSwitch: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StageUpdate.png',
  },
  threadMembers: {
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MemberUpdate.png',
  },
  stage: {
   open: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StageInstanceOpen.png',
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StageInstanceUpdate.png',
   close: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StageInstanceClose.png',
  },
  channel: {
   MediaChannelUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MediaChannelUpdate.png',
   MediaChannelCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MediaChannelCreate.png',
   MediaChannelDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MediaChannelDelete.png',
   GroupDmUpdate: emotes.updated.link,
   GroupDmDelete: emotes.deleted.link,
   GroupDmCreate: emotes.created.link,
   DMDelete: emotes.deleted.link,
   DMCreate: emotes.created.link,
   DMUpdate: emotes.updated.link,
   UnknownUpdate: emotes.updated.link,
   UnknownCreate: emotes.created.link,
   UnknownDelete: emotes.deleted.link,
   TextChannelCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/TextChannelCreate.png',
   ThreadCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ThreadCreate.png',
   VoiceCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/VoiceCreate.png',
   NewsChannelCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/NewsChannelCreate.png',
   NSFWChannelCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/NSFWChannelCreate.png',
   RulesCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/RulesCreate.png',
   StageCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StageCreate.png',
   CategoryCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/CategoryCreate.png',
   LockedChannelCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/LockedChannelCreate.png',
   LockedVoiceCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/LockedVoiceCreate.png',
   DirectoryCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/DirectoryCreate.png',
   ForumCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ForumCreate.png',
   NSFWForumCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/NSFWForumCreate.png',
   TextChannelDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/TextChannelDelete.png',
   ThreadDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ThreadDelete.png',
   VoiceDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/VoiceDelete.png',
   NewsChannelDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/NewsChannelDelete.png',
   NSFWChannelDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/NSFWChannelDelete.png',
   RulesDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/RulesDelete.png',
   StageDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StageDelete.png',
   CategoryDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/CategoryDelete.png',
   LockedChannelDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/LockedChannelDelete.png',
   LockedVoiceDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/LockedVoiceDelete.png',
   DirectoryDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/DirectoryDelete.png',
   ForumDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ForumDelete.png',
   NSFWForumDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/NSFWForumDelete.png',
   TextChannelUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/TextChannelUpdate.png',
   ThreadUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ThreadUpdate.png',
   VoiceUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/VoiceUpdate.png',
   NewsChannelUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/NewsChannelUpdate.png',
   NSFWChannelUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/NSFWChannelUpdate.png',
   RulesUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/RulesUpdate.png',
   StageUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StageUpdate.png',
   CategoryUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/CategoryUpdate.png',
   LockedChannelUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/LockedChannelUpdate.png',
   LockedVoiceUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/LockedVoiceUpdate.png',
   DirectoryUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/DirectoryUpdate.png',
   ForumUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ForumUpdate.png',
   NSFWForumUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/NSFWForumUpdate.png',
   Pin: 'https://cdn.ayakobot.com/Ayako_Assets/Events/PinCreate.png',
   Unpin: 'https://cdn.ayakobot.com/Ayako_Assets/Events/PinDelete.png',
   PinUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/PinUpdate.png',
  },
  emoji: {
   create: 'https://cdn.ayakobot.com/Ayako_Assets/Events/EmojiCreate.png',
   delete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/EmojiDelete.png',
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/EmojiUpdate.png',
  },
  sticker: {
   create: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StickerCreate.png',
   delete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StickerDelete.png',
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/StickerUpdate.png',
  },
  guild: {
   AuditLogCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/AuditLogCreate.png',
   BanCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/BanCreate.png',
   BanRemove: 'https://cdn.ayakobot.com/Ayako_Assets/Events/BanRemove.png',
   GuildCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/GuildCreate.png',
   GuildUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/GuildUpdate.png',
   GuildDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/GuildDelete.png',
   WebhookUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/WebhookUpdate.png',
   BotUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/BotUpdate.png',
   ChannelFollowUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ChannelFollowUpdate.png',
   SlashCommandUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/SlashCommandUpdate.png',
   WebhookDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/WebhookDelete.png',
   BotDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/BotDelete.png',
   ChannelFollowDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ChannelFollowDelete.png',
   SlashCommandDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/SlashCommandDelete.png',
   WebhookCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/WebhookCreate.png',
   BotCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/BotCreate.png',
   ChannelFollowCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ChannelFollowCreate.png',
   SlashCommandCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/SlashCommandCreate.png',
   MemberCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MemberCreate.png',
   MemberDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MemberDelete.png',
   MemberUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MemberUpdate.png',
   Prune: 'https://cdn.ayakobot.com/Ayako_Assets/Events/Prune.png',
   ScheduledEventCreate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ScheduledEventCreate.png',
   ScheduledEventDelete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ScheduledEventDelete.png',
   ScheduledEventUpdate: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ScheduledEventUpdate.png',
  },
  invite: {
   create: 'https://cdn.ayakobot.com/Ayako_Assets/Events/InviteCreate.png',
   delete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/InviteDelete.png',
  },
  message: {
   delete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MessageDelete.png',
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/MessageUpdate.png',
   Publish: 'https://cdn.ayakobot.com/Ayako_Assets/Events/Publish.png',
  },
  reaction: {
   create: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ReactionAdd.png',
   remove: 'https://cdn.ayakobot.com/Ayako_Assets/Events/ReactionRemove.png',
  },
  role: {
   create: 'https://cdn.ayakobot.com/Ayako_Assets/Events/RoleCreate.png',
   remove: 'https://cdn.ayakobot.com/Ayako_Assets/Events/RoleDelete.png',
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/RoleUpdate.png',
  },
  webhook: {
   create: 'https://cdn.ayakobot.com/Ayako_Assets/Events/WebhookCreate.png',
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/WebhookUpdate.png',
   delete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/WebhookDelete.png',
  },
  command: {
   create: 'https://cdn.ayakobot.com/Ayako_Assets/Events/SlashCommandCreate.png',
   delete: 'https://cdn.ayakobot.com/Ayako_Assets/Events/SlashCommandDelete.png',
   update: 'https://cdn.ayakobot.com/Ayako_Assets/Events/SlashCommandUpdate.png',
  },
 },
};
